export default {
  form: 'product-form',
  list: 'product-form__list',
  item: 'product-form__item',
  itemTiny: 'product-form__item--tiny',
  itemFollow: 'product-form__item--follow',
  itemFull: 'product-form__item--full',
  label: 'product-form__label',
  input: 'product-form__input',
  inputUpload: 'product-form__upload',
  inputUploadLoading: 'product-form__upload--loading',
  inputText: 'product-form__input--text',
  inputNumber: 'product-form__input--number',
  inputSelect: 'product-form__input--select',
  inputTextarea: 'product-form__input--textarea',
  imgsList: 'product-form__images-list',
  imgsItem: 'product-form__images-item',
  img: 'product-form__image',
  imgWrapper: 'product-form__image-wrapper',
  imgSource: 'product-form__image-source',
  imgRemove: 'product-form__image-remove',
  preview: 'product-form__preview',
  footer: 'product-form__footer',
  submit: 'product-form__submit'
};
